In [1]:
import sys
import os
from os.path import abspath
import numpy as np
import pandas as pd
from utils.generate_network import generate_network
from utils.prepare_data import prepare_data
from utils.popphy_io import save_params, load_params
from utils.popphy_io import get_stat, get_stat_dict
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_curve
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from models.PopPhy import PopPhyCNN
import warnings
from datetime import datetime
import json
import warnings
warnings.filterwarnings("ignore")

import tensorflow as tf
#from models.PopPhy2 import ResNet
from models.PopPhy2 import ResNet

# Data Preparation

### Reading Configuration
Configuring which data to read in, minimun threshold needed in an OTU (individual sample must have at least set threshold relative abundance), and how many k folds for k fold cross validation.

In [2]:
dataset = 'skg-wt-t1'
dataset2 = 'skg2-mtx-wt-t4'
threshold = 0
k = 1

### Reduce Features
Reduce amount of OTU features by filtering out OTUs that contain no individual sample with a relative abundance greater than the set threshold.

In [3]:
path = "../data/" + dataset
data = pd.read_csv(path + '/abundance.tsv', index_col=0, sep='\t', header=None)
to_drop = data.loc[(data < threshold).all(axis=1)]
data = data.drop(to_drop.index)


path2 = "../data/" + dataset2
data2 = pd.read_csv(path2 + '/abundance.tsv', index_col=0, sep='\t', header=None)
to_drop2 = data2.loc[(data2 < threshold).all(axis=1)]
data2 = data2.drop(to_drop.index)

# data = data.groupby(data.index).sum()

data

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,,,,,,,,,,,,,,,,,,
k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Bacteroidaceae|g__Bacteroides|s__Bacteroides_acidifaciens,35,712,107,0,616,609,1129,397,209,562,284,1923,989,815,1254,2941,1171,716
k__Bacteria|p__Proteobacteria|c__Gammaproteobacteria|o__Enterobacterales|f__Enterobacteriaceae|g__unclassified|s__unclassified_unclassified,0,0,9,0,0,0,0,0,0,0,0,355,0,2986,0,4,2,0
k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_murinus,294,258,318,258,403,446,914,761,6,1150,664,4588,1151,1660,3936,920,721,509
k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_johnsonii,15,135,92,470,125,54,30,26,52,1761,3105,866,679,430,2288,1161,2464,1215
k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Rikenellaceae|g__Alistipes|s__Alistipes_unclassified,46,106,12,373,52,73,98,0,13,971,518,181,130,998,777,92,28,185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
k__Bacteria|p__Firmicutes|c__Clostridia|o__Lachnospirales|f__Lachnospiraceae|g__Lachnospiraceae NK4A136 group|s__Lachnospiraceae NK4A136 group_unclassified,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Bacteroidaceae|g__Bacteroides|s__Bacteroides_unclassified,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Lachnospirales|f__Lachnospiraceae|g__unclassified|s__unclassified_unclassified,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Lachnospirales|f__Lachnospiraceae|g__unclassified|s__unclassified_unclassified,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Lachnospirales|f__Lachnospiraceae|g__unclassified|s__unclassified_unclassified,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
data2

,1,2,3,4,5,6,7,8
0,,,,,,,,
k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Bacteroidaceae|g__Bacteroides|s__Bacteroides_acidifaciens,487,95,1123,1378,129,450,444,1079
k__Bacteria|p__Proteobacteria|c__Gammaproteobacteria|o__Enterobacterales|f__Enterobacteriaceae|g__unclassified|s__unclassified_unclassified,0,0,0,0,0,0,0,0
k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_murinus,363,91,516,543,120,74,440,1777
k__Bacteria|p__Firmicutes|c__Bacilli|o__Lactobacillales|f__Lactobacillaceae|g__Lactobacillus|s__Lactobacillus_johnsonii,5984,1076,2606,1303,735,7,2410,2406
k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Rikenellaceae|g__Alistipes|s__Alistipes_unclassified,8473,415,586,576,3581,1564,493,155
...,...,...,...,...,...,...,...,...
k__Bacteria|p__Firmicutes|c__Clostridia|o__Lachnospirales|f__Lachnospiraceae|g__Lachnospiraceae NK4A136 group|s__Lachnospiraceae NK4A136 group_unclassified,0,0,0,0,0,0,0,0
k__Bacteria|p__Bacteroidota|c__Bacteroidia|o__Bacteroidales|f__Bacteroidaceae|g__Bacteroides|s__Bacteroides_unclassified,0,0,0,0,0,0,0,0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Lachnospirales|f__Lachnospiraceae|g__unclassified|s__unclassified_unclassified,0,0,0,0,0,0,0,0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Lachnospirales|f__Lachnospiraceae|g__unclassified|s__unclassified_unclassified,0,0,0,0,0,0,0,0
k__Bacteria|p__Firmicutes|c__Clostridia|o__Lachnospirales|f__Lachnospiraceae|g__unclassified|s__unclassified_unclassified,0,0,0,0,0,0,0,0

### Create 2d Matrix Representing OTU Data
Dai et al. PopPhy-CNN's (2019) algorithm creates Phylogenetic tree from OTUs and populates tree based on OTU abundances. This tree graph structure is then converted to a 2d Matrix by taking each parent node in the tree graph and pushing them all to the left and childrens' nodes in the same order from left to right the parents were ordered.

In [5]:
my_maps, raw_x, tree_x, raw_features, tree_features, labels, label_set, g, feature_df = prepare_data(path, data)

# norms = np.linalg.norm(my_maps, axis=2, keepdims=True)
# my_maps = my_maps / norms
pd.DataFrame(my_maps[0])

(1379, 18)
There are 1379 raw features...
Building tree structure...
Found tree file...
Populating trees...
There are 432 tree features...

,0,1,2,3,4,5,6,7,8,9,...,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140
0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.014875,0.357585,0.046097,0.001915,0.078645,0.498527,0.002356,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.014875,0.100589,0.031811,0.000000,0.225184,0.046097,0.000000,0.001915,0.078645,0.465685,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.014875,0.006186,0.094404,0.031811,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.014875,0.006186,0.094404,0.000295,0.031517,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.014875,0.006186,0.094404,0.000295,0.031517,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.014875,0.000000,0.006186,0.000000,0.000000,0.000000,0.000000,0.094404,0.000295,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
my_maps2, raw_x2, tree_x2, raw_features2, tree_features2, labels2, label_set2, g2, feature_df2 = prepare_data(path2, data2)
pd.DataFrame(my_maps2[0])

(1379, 8)
There are 1379 raw features...
Building tree structure...
Found tree file...
Populating trees...
There are 432 tree features...

,0,1,2,3,4,5,6,7,8,9,...,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140
0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.000000,0.263036,0.214894,0.000089,0.000000,0.508157,0.013823,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.104627,0.000374,0.000000,0.158035,0.214894,0.000089,0.000000,0.0,0.500898,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,0.021046,0.083581,0.000374,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.000000,0.021046,0.083581,0.000000,0.000374,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.000000,0.021046,0.083581,0.000000,0.000374,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.000000,0.007935,0.013112,0.000000,0.000000,0.000000,0.000000,0.083581,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.007935,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Creating training and test sets
Splitting data into k training and k test sets

In [7]:
#one hot encoding
input = my_maps
target = tf.keras.utils.to_categorical(labels, 2, dtype='int64')

input2 = my_maps2
target2 = tf.keras.utils.to_categorical(labels2, 2, dtype='int64')
    

# x_train = input
# y_train = target
# x_test = input2
# y_test = target2

train_x = input
train_y = target
test_x = input2
test_y = target2
    
model = ResNet(height = train_x.shape[1], width = train_x.shape[2], channels = 1, classes = 2)
model.init_model()
model.train(train_x, train_y, test_x, test_y, dataset, use_weights = False)
y_pred = model.predict(test_x)

# auc_roc, auc_pr, f1, mcc = model.evaluate(test_y, y_pred)
# data_lst.append([auc_roc, auc_pr, f1, mcc])

#model.model.save_weights(path + "/model_weights.h5")
# print(test_y)
# print(y_pred)
# print(model.model.summary())
    
# #shuffle dataset
# seed = np.random.randint(100)
# # np.random.seed(seed)
# # np.random.shuffle(input)
# np.random.seed(seed)
# np.random.shuffle(target)

# np.random.seed(seed)
# np.random.shuffle(my_maps)
# np.random.seed(seed)
# np.random.shuffle(raw_x)
# np.random.seed(seed)
# np.random.shuffle(tree_x)
# np.random.seed(seed)
# np.random.shuffle(labels)


# #create k training and k test sets
# groups_input = []
# groups_target = []
# k_size = len(input)//k
# start, end = 0, k_size
# for i in range(k):
#     if i == k-1:
#         group_input = input[start:]
#         group_target = target[start:]
#     else:
#         group_input = input[start:end]
#         group_target = target[start:end]
#     start += k_size
#     end += k_size
#     groups_input.append(group_input)
#     groups_target.append(group_target)

# x_train = []
# y_train = []
# x_test = []
# y_test = []
# for i in range(k-1, -1, -1):
#     x_train.append(np.concatenate((groups_input[i-1], groups_input[i-2], groups_input[i-3], groups_input[i-4])))
#     y_train.append(np.concatenate((groups_target[i-1], groups_target[i-2], groups_target[i-3], groups_target[i-4])))

#     x_test.append(groups_input[i])
#     y_test.append(groups_target[i])

Metal device set to: Apple M1 Pro
Epoch 1/12
9/9 [==============================] - 2s 138ms/step - loss: 2.8706 - accuracy: 0.3889 - val_loss: 1.6966 - val_accuracy: 1.0000
Epoch 2/12
9/9 [==============================] - 0s 47ms/step - loss: 1.7784 - accuracy: 0.5000 - val_loss: 1.1038 - val_accuracy: 1.0000
Epoch 3/12
9/9 [==============================] - 0s 41ms/step - loss: 1.3082 - accuracy: 0.5000 - val_loss: 0.7820 - val_accuracy: 1.0000
Epoch 4/12
9/9 [==============================] - 0s 45ms/step - loss: 0.9945 - accuracy: 0.5000 - val_loss: 0.7174 - val_accuracy: 1.0000
Epoch 5/12
9/9 [==============================] - 0s 40ms/step - loss: 0.8822 - accuracy: 0.5000 - val_loss: 0.7504 - val_accuracy: 1.0000
Epoch 6/12
9/9 [==============================] - 0s 42ms/step - loss: 0.8205 - accuracy: 0.5000 - val_loss: 0.7802 - val_accuracy: 1.0000
Epoch 7/12
9/9 [==============================] - 0s 40ms/step - loss: 0.7833 - accuracy: 0.5000 - val_loss: 0.7720 - val_accuracy: 0.6250
Epoch 8/12
9/9 [==============================] - 0s 48ms/step - loss: 0.7627 - accuracy: 0.5000 - val_loss: 0.7286 - val_accuracy: 1.0000
Epoch 9/12
9/9 [==============================] - 0s 48ms/step - loss: 0.7528 - accuracy: 0.5000 - val_loss: 0.6888 - val_accuracy: 1.0000
Epoch 10/12
9/9 [==============================] - 0s 42ms/step - loss: 0.7429 - accuracy: 0.5000 - val_loss: 0.6542 - val_accuracy: 1.0000
Epoch 11/12
9/9 [==============================] - 0s 40ms/step - loss: 0.7454 - accuracy: 0.2778 - val_loss: 0.6183 - val_accuracy: 1.0000
Epoch 12/12
9/9 [==============================] - 0s 45ms/step - loss: 0.7319 - accuracy: 0.5000 - val_loss: 0.6167 - val_accuracy: 1.0000
1/1 [==============================] - 0s 121ms/step

In [8]:
print(test_y)
print(y_pred)
print(model.model.summary())

[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]]
[[0.61696464 0.38303542]
 [0.62243044 0.3775696 ]
 [0.6229615  0.37703845]
 [0.6279943  0.3720057 ]
 [0.61401594 0.38598415]
 [0.61979353 0.38020647]
 [0.62152654 0.3784735 ]
 [0.6278078  0.3721922 ]]
Model: "res"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_1 (InputLayer)           [(None, 11, 1141, 1  0           []
                                )]

 res2a-conv1 (Conv2D)           (None, 11, 1141, 64  576         ['input_1[0][0]']
                                )

 res2a-batchnorm1 (BatchNormali  (None, 11, 1141, 64  256        ['res2a-conv1[0][0]']
 zation)                        )

 activation (Activation)        (None, 11, 1141, 64  0           ['res2a-batchnorm1[0][0]']
                                )

 res2a-conv2 (Conv2D)           (None, 11, 1141, 64  32832       ['activation[0][0]']
                                )

 res2a-batchnorm2 (BatchNormali  (None, 11, 1141, 64  256        ['res2a-conv2[0][0]']
 zation)                        )

 add (Add)                      (None, 11, 1141, 64  0           ['res2a-batchnorm2[0][0]',
                                )                                 'input_1[0][0]']

 activation_1 (Activation)      (None, 11, 1141, 64  0           ['add[0][0]']
                                )

 res2b-conv1 (Conv2D)           (None, 11, 1141, 64  32832       ['activation_1[0][0]']
                                )

 res2b-batchnorm1 (BatchNormali  (None, 11, 1141, 64  256        ['res2b-conv1[0][0]']
 zation)                        )

 activation_2 (Activation)      (None, 11, 1141, 64  0           ['res2b-batchnorm1[0][0]']
                                )

 res2b-conv2 (Conv2D)           (None, 11, 1141, 64  32832       ['activation_2[0][0]']
                                )

 res2b-batchnorm2 (BatchNormali  (None, 11, 1141, 64  256        ['res2b-conv2[0][0]']
 zation)                        )

 add_1 (Add)                    (None, 11, 1141, 64  0           ['res2b-batchnorm2[0][0]',
                                )                                 'activation_1[0][0]']

 activation_3 (Activation)      (None, 11, 1141, 64  0           ['add_1[0][0]']
                                )

 conv2 (Conv2D)                 (None, 11, 1141, 1)  577         ['activation_3[0][0]']

 flatten (Flatten)              (None, 12551)        0           ['conv2[0][0]']

 fc (Dense)                     (None, 100)          1255200     ['flatten[0][0]']

 softmax (Dense)                (None, 2)            202         ['fc[0][0]']

==================================================================================================
Total params: 1,356,075
Trainable params: 1,355,563
Non-trainable params: 512
__________________________________________________________________________________________________
None

# Model

### Training model
Data is log transformed and then a MinMax transformation. Uses CNN that employs skipped residual identity blocks borrowed from the classic ResNet model then a FC Neural Network to make phenotype prediction. Model dimensions printed below.

In [9]:
data_lst = []

# for i in range(k):
#     x_train1 = x_train[i]
#     y_train1 = y_train[i]
#     x_test1 = x_test[i]
#     y_test1 = y_test[i]

#     model = ResNet(height = x_train1.shape[1], width = x_train1.shape[2], channels = 1, classes = 2)
#     model.init_model()

#     model.train(x_train1, y_train1, x_test1, y_test1, dataset, use_weights = False)
#     y_pred = model.predict(x_test1)
#     auc_roc, auc_pr, f1, mcc = model.evaluate(y_test1, y_pred)
#     data_lst.append([auc_roc, auc_pr, f1, mcc])
    
#     #model.model.save_weights(path + "/model_weights.h5")

#     print(y_test1)
#     print(y_pred)
    
# print(model.model.summary())



n_values = np.max(labels) + 1
labels_oh = np.eye(n_values)[labels]
tree_row = my_maps.shape[1]
tree_col = my_maps.shape[2]

skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=seed)
fold = 0
for train_index, test_index in skf.split(my_maps, labels):
    train_x, test_x = my_maps[train_index,:,:], my_maps[test_index,:,:]
    train_y, test_y = labels_oh[train_index,:], labels_oh[test_index,:]
        
    train_x = np.log(train_x + 1)
    test_x = np.log(test_x + 1)
        
    c_prob = [0] * len(np.unique(labels))
    train_weights = []

    for l in np.unique(labels):
        a = float(len(labels))
        b = 2.0 * float((np.sum(labels==l)))
        c_prob[int(l)] = a/b

    c_prob = np.array(c_prob).reshape(-1)

    for l in np.argmax(train_y, 1):
        train_weights.append(c_prob[int(l)])
    train_weights = np.array(train_weights)
        
    scaler = MinMaxScaler().fit(train_x.reshape(-1, tree_row * tree_col))
    train_x = np.clip(scaler.transform(train_x.reshape(-1, tree_row * tree_col)), 0, 1).reshape(-1, tree_row, tree_col)
    test_x = np.clip(scaler.transform(test_x.reshape(-1, tree_row * tree_col)), 0, 1).reshape(-1, tree_row, tree_col)

    train = [train_x, train_y]
    test = [test_x, test_y]

    x_train1 = train_x
    y_train1 = train_y
    x_test1 = test_x
    y_test1 = test_y
        
#         y_train1 = train_y
#         y_test1 = test_y
        
#         x_train1 = np.zeros(train_x.shape)
#         x_train1[train_x != 0] = 1
        
#         x_test1 = np.zeros(test_x.shape)
#         x_test1[test_x != 0] = 1
        
        # for i in range(len(train_x)):
        #     for j in range(len(test_x)):
        #         if np.array_equal(train_x[i], test_x[j]):
        #             print('train')
        #             print(train_x[i])
        #             print('test')
        #             print(test_x[j])
        
        
    model = ResNet(height = train_x.shape[1], width = train_x.shape[2], channels = 1, classes = 2)
    model.init_model()
    model.train(train_x, train_y, test_x, y_test1, dataset, use_weights = False)
    y_pred = model.predict(test_x)
    auc_roc, auc_pr, f1, mcc = model.evaluate(test_y, y_pred)
    data_lst.append([auc_roc, auc_pr, f1, mcc])
    #model.model.save_weights(path + "/model_weights.h5")
    print(test_y)
    print(y_pred)
    print(model.model.summary())
    
    fold += 1
#run += 1

NameError: name 'seed' is not defined

# Displaying Accuracy Metrics and Saving Metrics

Option to save results of all k folds and weights of last model into same directy as data.

In [ ]:
col = [str(i) for i in range(1,k+1)]    
results_df = pd.DataFrame(data_lst, columns = ['auc(roc)', 'auc(pr)', 'f1', 'mcc'])
results_df = results_df.transpose()
results_df.columns = col

#results_df.to_csv(path + "/results.csv")
results_df

# Saving Model Weights

Option to save model weights of last model in k fold into same directy as data.

In [ ]:
#model.model.save_weights(path + "/model_weights.h5")

##